#!/bin/sh
  
set -e
set -u

: "${CONTAINER_UID:=0}"
: "${CONTAINER_GID:=${CONTAINER_UID}}"

if [ "$#" = 0 ]
then set -- zsh -l
fi

if [ "$CONTAINER_UID" != 0 ]
then
        usermod -u "$CONTAINER_UID" "$DOCKER_USER" 2>/dev/null
        groupmod -g "$CONTAINER_GID" "$DOCKER_USER" 2>/dev/null || usermod -a -G "$CONTAINER_GID" "$DOCKER_USER"
        set -- gosu "${CONTAINER_UID}:${CONTAINER_GID}" "${@}"
fi

exec "$@"
